export function renderCustomerDetails(detail, { escapeText, formatDate, formatDataUsage, money, status }) {
  if (!detail) return '';
  const value = entry => escapeText(entry == null || entry === '' ? 'Not reported' : String(entry));
  const row = (label, entry) => `<div><dt>${escapeText(label)}</dt><dd>${value(entry)}</dd></div>`;
  const customer = detail.data?.customer || detail.user;
  const connections = detail.data?.connections;
  const apNames = [...new Set((connections?.accessPoints || []).map(ap => ap.name))];
  const attribute = entry => escapeText(String(entry ?? '')).replaceAll('"', '&quot;');
  const deviceForm = (device = {}, session = null) => `<form data-customer-device class="customer-device-form"><h3>Save device details</h3><label>Device MAC address<input name="macAddress" value="${attribute(device.macAddress || session?.['mac-address'] || '')}" required maxlength="30" placeholder="AA:BB:CC:DD:EE:FF" /></label><label>Device type<select name="deviceType"><option value="">Unknown / use hostname hint</option>${(detail.data?.deviceTypes || []).map(type => `<option value="${attribute(type)}" ${device.deviceType === type ? 'selected' : ''}>${escapeText(type)}</option>`).join('')}</select></label><label>Device model<input name="deviceModel" value="${attribute(device.deviceModel || '')}" maxlength="100" placeholder="e.g. Samsung Galaxy A15, iPhone 15" /></label><label>Recorded access point<input name="accessPoint" list="customer-ap-names" value="${attribute(device.accessPoint || session?.accessPoint || '')}" maxlength="100" placeholder="Select or enter an access point" /></label><button class="secondary-button" type="submit">Save AP &amp; device type</button><p data-customer-save-status role="status"></p></form>`;
  return `<div class="modal-backdrop"><section class="modal customer-details" role="dialog" aria-modal="true" aria-labelledby="customer-details-title" tabindex="-1"><button type="button" class="close-button" data-close-customer aria-label="Close customer details">×</button><p class="eyebrow">CUSTOMER DETAILS</p><h2 id="customer-details-title">${value(customer.username)}</h2>
    <dl class="customer-detail-grid">${row('Phone', customer.phone)}${row('Plan', detail.data?.plan || detail.plan)}${row('Status', status(customer))}${row('Amount paid', money(customer.amount))}${row('Data used', formatDataUsage(customer.dataConsumedBytes))}${row('Data limit', `${customer.dataLimit || 0} GB`)}${row('Created', formatDate(customer.createdAt))}${row('First login', customer.activatedAt ? formatDate(customer.activatedAt) : 'Not recorded')}${row('Expiry', customer.expiresAt ? formatDate(customer.expiresAt) : 'Not recorded')}${row('Payment reference', customer.paymentReference)}${row('Source', customer.source)}${row('Last reported town', customer.lastTownId)}</dl>
    ${detail.loading ? '<p role="status">Reading connection and device details from the router…</p>' : detail.error ? `<p role="alert">${escapeText(detail.error)}</p>` : `<h3>Connection on this town's router: ${connections?.connected === null ? 'Unknown' : connections?.connected ? 'Online' : 'Offline'}</h3>${connections?.connected === false ? '<p>No active session was found on this town’s router.</p>' : ''}${(connections?.sessions || []).map((session, index) => `<section class="customer-session"><h3>Device ${index + 1}</h3><dl class="customer-detail-grid">${row('Access point', session.accessPoint)}${row('AP interface', session.accessPointDetails?.interface || session.wireless?.interface)}${row('AP address', session.accessPointDetails?.address)}${row('AP model', session.accessPointDetails?.model)}${row('Device hostname', session.deviceName)}${row('Device type', session.deviceType)}${row('Device model', session.deviceModel)}${row('IP address', session.address)}${row('MAC address', session['mac-address'])}${row('Hotspot server', session.server)}${row('Bridge port', session.bridgePort)}${row('Session uptime', session.uptime)}${row('Session time left', session['session-time-left'])}${row('Idle time', session['idle-time'])}${row('Login method', session['login-by'])}${row('Upload', formatDataUsage(session['bytes-in']))}${row('Download', formatDataUsage(session['bytes-out']))}${Object.entries(session.wireless || {}).map(([label, entry]) => row(label, entry)).join('')}${Object.entries(session.dhcp || {}).map(([label, entry]) => row(`DHCP ${label}`, entry)).join('')}</dl><p>${escapeText(session.accessPointNote)}</p><p>${escapeText(session.deviceTypeNote)}</p></section>`).join('')}${connections?.warnings?.length ? `<details><summary>Some router tables could not be read</summary>${connections.warnings.map(warning => `<p>${escapeText(warning)}</p>`).join('')}</details>` : ''}${detail.data?.checkedAt ? `<p>Checked ${escapeText(formatDate(detail.data.checkedAt))}</p>` : ''}`}
    ${detail.data ? `<section class="customer-ap-catalog"><h3>Access points in this town</h3><datalist id="customer-ap-names">${apNames.map(name => `<option value="${attribute(name)}"></option>`).join('')}</datalist>${(connections?.accessPoints || []).map(ap => `<dl class="customer-detail-grid">${row('Access point name', ap.name)}${row('AP interface', ap.interface)}${row('AP address', ap.address)}${row('AP model', ap.model)}${row('Radio MAC', ap.radioMac)}${row('SSID', ap.ssid)}${row('Information source', ap.source)}</dl>`).join('') || '<p>No AP names are reported yet. Add your external access points below.</p>'}<form data-customer-ap class="customer-device-form"><h3>Add or update access point</h3><label>AP name<input name="name" required maxlength="100" list="customer-ap-names" placeholder="e.g. Market AP, Main station AP" /></label><label>Wireless interface (if reported)<input name="interface" maxlength="100" placeholder="e.g. cap1, wifi1" /></label><label>AP IP address<input name="address" maxlength="100" placeholder="e.g. 192.168.10.20" /></label><label>AP model<input name="model" maxlength="100" placeholder="e.g. MikroTik cAP ax, TP-Link EAP225" /></label><button class="secondary-button" type="submit">Save access point</button><p data-customer-save-status role="status"></p></form></section><section><h3>Device types &amp; models</h3><p>Choose the known device type and record its model. Saved AP assignments are manager records; live wireless matches show the current AP.</p>${(connections?.sessions || []).map(session => deviceForm(session.savedDevice || {}, session)).join('')}${(detail.data.savedDevices || []).filter(device => !(connections?.sessions || []).some(session => String(session['mac-address'] || '').replace(/[^a-f0-9]/gi, '').toUpperCase() === device.macAddress)).map(device => `<dl class="customer-detail-grid">${row('Saved device MAC', device.macAddress)}${row('Device type', device.deviceType)}${row('Device model', device.deviceModel)}${row('Recorded access point', device.accessPoint)}</dl>${deviceForm(device)}`).join('')}<details><summary>Add another device</summary>${deviceForm()}</details></section>` : ''}
    <button class="secondary-button" data-refresh-customer ${detail.loading ? 'disabled' : ''}>Refresh connection details</button></section></div>`;
}
